title: FounderFlirt
author: Lasse Schuirmann
email: lasse@viperdev.io
description: > # this means to ignore newlines until "baseurl:"
  FounderFlirt helps connecting

twitter_username: viperdev_io
github_username:  viper-development

sass:
    style: compressed
